### ISSUE TITLE
Go Support?

### ISSUE THREAD

**Issue by jontstaz** [awekrx/AutoDoc-ChatGPT#1]
Hey mate,

Great work on this repo, I've been looking for something like this! Is there any chance you're going to implement support for Go anytime soon? That'd be super useful for me and I'm sure many others. Thanks in advance.

**Comment by awekrx** [comment]
Hey, yes, Go support is planned. I just wanted to implement this after TS and JS. I don't know how long it will take, if ChatGPT does not produce random results, as with TS now, then it will be ready within 1 week.
