### ISSUE TITLE
Feedback into ChatGPT based on Pre-commit and pytest?

### ISSUE THREAD

**Issue by a-t-0** [awekrx/AutoDoc-ChatGPT#2]
Thank you for creating such a wonderful project! I [planned](https://github.com/HiveMinds/ChatGPT-documentation-tests/issues/1) to create a simular application, that includes the generation of tests.

## Observations
 - After interacting with ChatGPT for a while, I noticed it would often require some encouragements of me to create a complete function/response. (E.g. it would only return half of the expected function, and after asking it 5 times, "please finish it", it would (eventually)).
 - I noticed its solutions were often not compliant with (strict) [pre-commit](https://github.com/pre-commit/pre-commit) requirements ([e.g.](https://github.com/HiveMinds/python-template)). However, after it was given the feedback of the `pre-commit` violations, e.g. line-length violations by python black, or missing type-hints, it would often correct itself.

## Question
Hence, I would like to ask:

would you be willing to enhance this repository to facilitate automatic feedback into chatgpt based on pre-commit output? 

(Example output:)
![image](https://user-images.githubusercontent.com/34750068/222987613-f49af2b9-1966-4b05-b31e-5381be14204f.png)

For completeness, a detailed suggestion on how such a feedback could be realised can be found in [here](https://github.com/HiveMinds/ChatGPT-documentation-tests/issues/1), and perhaps you have different ideas :)

Ps. If you have any questions on pre-commit or otherwise, feel free to reach out!

**Comment by awekrx** [comment]
Hello, unfortunately I don't have much time right now to help you with development. So far, I still have a lot of work with AutoDoc that I spend my free time on. But I can tell you about making requests to ChatGPT, if you are interested, then write to me on [Telegram](https://t.me/awekrx).
